### ISSUE TITLE
allpermid.txt in output

### ISSUE THREAD

**Issue by rbeezer** [davidfarmer/LaTeXtoLaTeX#14]
Placing permid's onto source creates `allpermid.txt` in the output directory.

Would it be wise to figure out some way to make it less likely that an author gets it into their repository and mistakenly commits it?

Perhaps use a flag/option that will cause it to be created, so the default is not to?

**Comment by davidfarmer** [comment]
That file is only of limited use now.  What I want it to be is the
tree of permids.  But that needs to be done with an XSLT after the
permids are added.

I think I'll stop writng that file.

**Comment by davidfarmer** [comment]
File no longer written.
