### ISSUE TITLE
Pretty-printing a PreTeXt "c" element

### ISSUE THREAD

**Issue by rbeezer** [davidfarmer/LaTeXtoLaTeX#15]
A "c" element is inline verbatim, and there is no way to manipulate whitespace in any way.  So
```xml
<c>foo</c>
```
pretty-printed as
```xml
<c>
  foo
</c>
```
will introduce (unwanted) newlines and whitespace that will be reproduced by the output format's verbatim mechanisms.  In particular, a long `c` should not be line-broken.  Search on "impinge" in the PreTeXt sample article for a long example.

I built HTML output for the sample article.  Then pretty-printed the sample article and built HTML output.  Then did a `git diff` with `--word-diff` which will not show all the double spaces at sentence-end which become single spaces.

**Comment by davidfarmer** [comment]
The prettyprinter is not supposed to touch the "c" markup,
and I just checked that it left it all inline when ORCCA was
prettyprinted.

Did this somehow happen in AATA?

**Comment by rbeezer** [comment]
Good.  Nothing in AATA that I can tell.  

I think I got the `c` and `cd` examples confused in this report - had about five things to report in different places.  Sorry for the inaccuracy.  But there is a problem with `c` that prompted this.

In the sample article, search for "very long snippet" in the raw version and in a pretty-print version.  It gets new line breaks.  Yes, nobody should be doing that, but best not to be changing it anyway.

**Comment by davidfarmer** [comment]
c content now treated as verbatim.

Checked on the sample article, but a double check woudl be welcome.

**Comment by rbeezer** [comment]
> Checked on the sample article, but a double check woudl be welcome.

Sample article looks good, and I built the LaTeX output and it looks great also.
