### ISSUE TITLE
Pretty-printing a PreTeXt "cd" element

### ISSUE THREAD

**Issue by rbeezer** [davidfarmer/LaTeXtoLaTeX#16]
Similar to the `c` element,

```xml
<cd>foo</cd>
```
is verbatim and all whitespace is meant to be significant.  It is rendered as a display.  So the pretty-printed version introduces extra whitespace.

It can be structured with the `line` element.  So the following is possible:
```xml
<cd>
  <line>foo</line>
  <line>bar</line>
</cd>
```
and might ohnly contain a single `line` element.  So `cd` is much like `me` and `cd\line` is like `md\mrow` **except** we can't mess with whitespace that might be significant in context.  Search sample article for `kng2` (case-insensitive) for an example of the first form.

I did not see anything similar with `pre` but it is in the same spirit.

**Comment by davidfarmer** [comment]
cd is no longer prettyprinted

open a new issue if something special has to happen for cd containing line.

**Comment by rbeezer** [comment]
Looks good.  Thanks.
