### ISSUE TITLE
Pretty-printing index entries and notation

### ISSUE THREAD

**Issue by rbeezer** [davidfarmer/LaTeXtoLaTeX#17]
The PreTeXt `idx` and `notation` elements are meant to be placed **anywhere** in a paragraph `p`.  They have an obvious purpose, but never render anything the reader sees where they are located.  So invisible, in a sense.

Whitespace, before and after, could be significant, such as a space between words.  So I cannot see a 100% correct strategy for sanitizing its surroundings.

When pretty-printed on a line of its own, especially at the start or end of a `p` introduces whitespace before and after.  One of these will be stripped (before at p start, after at p end).  The other is more problematic.

I feel like these need to keep the location an author has assigned, but despite a whole lot of thought, can't be certain there isn't a way out.

**Comment by rbeezer** [comment]
An extreme example from AATA, which in output is resulting in an extra space in front of the colon,
```xml
      From <xref ref="theorem-orbit"/>, we obtain the
      <term>class equation</term>
          <idx><h>Class equation</h></idx>
      :
      <me>
        |G| = |Z(G)| + [G: C(x_1) ] + \cdots + [ G: C(x_k)]
      </me>.
      One of the consequences of the class equation is that the order of each conjugacy class must divide the order of <m>G</m>.
```

**Comment by davidfarmer** [comment]
There was code that moved idx immediately prior to punctuation,
to immediately after it.  But it only did it for period and comma.
Now it also does it for ;:!? .

A diff on AATA revealed a few additional cases, for which I will send a 
pull request.

**Comment by davidfarmer** [comment]
The idx before punctuation is okay now.

I don'y fully understand the issue of an idx on its own line at the start of a p,
but I am closing this because I don't think it is a prettyprinting issue.
(If it is, lets start a new issue, and figure out where in the p the prettyprinter should move
those idx's)
