### ISSUE TITLE
Suggestions for pretty-printing PreTeXt "cd"

### ISSUE THREAD

**Issue by rbeezer** [davidfarmer/LaTeXtoLaTeX#18]
Follow-on to #16.

OK, `cd` is structured with `cline` (not `line`).  The `cline` part is verbatim and cannot be massaged.  Suggestions for pretty-printing, which are suggestive of how the output will render.

For single-shot `cd`

```xml
blah blah
<cd>verbatim<cd>
foo bar
```

For `cd/cline`, mimick `md/mrow`,

```xml
blah blah
<cd>
  <cline>verbatim</cline>
  <cline>verbatim</cline>
<cd>
foo bar
```

**Comment by davidfarmer** [comment]
cd and cline are now prettyprinted as recommended
