### ISSUE TITLE
XML comments

### ISSUE THREAD

**Issue by rbeezer** [davidfarmer/LaTeXtoLaTeX#19]
Judson's AATA had:

```xml
<p>Let <m>X</m> be a finite <m>G</m>-set and <m>X_G</m><!--NOTATION TABLE\label{noteXG}--> be the set of fixed points in <m>X</m>;
```
When pretty-printed, the space after the XML comment was removed, leaving no space between the `m` and the word "be".

PreTeXt does nothing with XML comments, the  xsltproc  processor just drops them.  Unclear to me what the best rearrangement is.  Putting mid-paragraph comments on their own line may give rise to some of the "extra" spaces we are seeing around `idx` and `notation`.

For this isolated case, I'm just moving this comment out of the paragraph.

**Comment by davidfarmer** [comment]
I had underestimated the "creative" ways in which people might
use comments.  I added a general fix for comments embedded in a
line of content, which handles this case properly.  A diff found
only one other case, which will be fixed in a pull request.
